export default {
  user: {
    username: "test-user-1",
    email: "test-user@example.com",
  },
  cars: [
    {
      id: 1,
      name: "chevrolet chevelle malibu",
      mpg: 18,
      cylinders: 8,
      horsepower: 130,
    },
    {
      id: 2,
      name: "buick skylark 320",
      mpg: 15,
      cylinders: 8,
      horsepower: 165,
    },
    {
      id: 3,
      name: "plymouth satellite",
      mpg: 18,
      cylinders: 8,
      horsepower: 150,
    },
    {
      id: 4,
      name: "amc rebel sst",
      mpg: 16,
      cylinders: 8,
      horsepower: 150,
    },
    {
      id: 5,
      name: "ford torino",
      mpg: 17,
      cylinders: 8,
      horsepower: 140,
    },
    {
      id: 6,
      name: "ford galaxie 500",
      mpg: 15,
      cylinders: 8,
      horsepower: 198,
    },
    {
      id: 7,
      name: "chevrolet impala",
      mpg: 14,
      cylinders: 8,
      horsepower: 220,
    },
    {
      id: 8,
      name: "plymouth fury iii",
      mpg: 14,
      cylinders: 8,
      horsepower: 215,
    },
    {
      id: 9,
      name: "pontiac catalina",
      mpg: 14,
      cylinders: 8,
      horsepower: 225,
    },
    {
      id: 10,
      name: "amc ambassador dpl",
      mpg: 15,
      cylinders: 8,
      horsepower: 190,
    },
    {
      id: 11,
      name: "citroen ds-21 pallas",
      mpg: "unknown",
      cylinders: 4,
      horsepower: 115,
    },
    {
      id: 12,
      name: "chevrolet chevelle concours (sw)",
      mpg: "unknown",
      cylinders: 8,
      horsepower: 165,
    },
    {
      id: 13,
      name: "ford torino (sw)",
      mpg: "unknown",
      cylinders: 8,
      horsepower: 153,
    },
    {
      id: 14,
      name: "plymouth satellite (sw)",
      mpg: "unknown",
      cylinders: 8,
      horsepower: 175,
    },
    {
      id: 15,
      name: "amc rebel sst (sw)",
      mpg: "unknown",
      cylinders: 8,
      horsepower: 175,
    },
    {
      id: 16,
      name: "dodge challenger se",
      mpg: 15,
      cylinders: 8,
      horsepower: 170,
    },
    {
      id: 17,
      name: "plymouth 'cuda 340",
      mpg: 14,
      cylinders: 8,
      horsepower: 160,
    },
    {
      id: 18,
      name: "ford mustang boss 302",
      mpg: "unknown",
      cylinders: 8,
      horsepower: 140,
    },
    {
      id: 19,
      name: "chevrolet monte carlo",
      mpg: 15,
      cylinders: 8,
      horsepower: 150,
    },
    {
      id: 20,
      name: "buick estate wagon (sw)",
      mpg: 14,
      cylinders: 8,
      horsepower: 225,
    },
  ],
};
